// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.donation.eoy.version.viewed", 4);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1706606957);
user_pref("app.update.lastUpdateTime.region-update-timer", 1706606957);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1706606957);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1706606987);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1706606957);
user_pref("browser.region.update.updated", 1702634367);
user_pref("browser.search.region", "IN");
user_pref("calendar.caldav.googleResync", 1702634365);
user_pref("calendar.list.sortOrder", "0b9313c0-40af-4df7-ae12-6d39e1659770");
user_pref("calendar.registry.0b9313c0-40af-4df7-ae12-6d39e1659770.calendar-main-default", true);
user_pref("calendar.registry.0b9313c0-40af-4df7-ae12-6d39e1659770.calendar-main-in-composite", true);
user_pref("calendar.registry.0b9313c0-40af-4df7-ae12-6d39e1659770.disabled", true);
user_pref("calendar.registry.0b9313c0-40af-4df7-ae12-6d39e1659770.name", "Home");
user_pref("calendar.registry.0b9313c0-40af-4df7-ae12-6d39e1659770.type", "storage");
user_pref("calendar.registry.0b9313c0-40af-4df7-ae12-6d39e1659770.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Asia/Kolkata");
user_pref("calendar.timezone.useSystemTimezone", true);
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1702634375394");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1706607008);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20231215200246");
user_pref("extensions.lastAppVersion", "115.6.0");
user_pref("extensions.lastPlatformVersion", "115.6.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"8ff82a46-9718-4bd2-a626-9749ba7ba992\",\"google@search.mozilla.org\":\"0ad9cf53-a916-481f-8047-ce2f7e52add0\",\"ddg@search.mozilla.org\":\"07921bc7-1b41-4922-b552-f69dbeea5049\",\"amazondotcom@search.mozilla.org\":\"18bb16a2-93b1-4bf0-b0a0-6a5046e44f5f\",\"wikipedia@search.mozilla.org\":\"dfcab597-7ddb-4f4b-b64d-835fe4658829\",\"bing@search.mozilla.org\":\"09b8a9f6-7d20-4e0f-b698-5d99cae5aa22\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1706607130);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 40);
user_pref("mailnews.database.global.datastore.id", "c7a5a307-7d04-4d7a-a957-ef68cafc292");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "115.6.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1706607130);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1706607130);
user_pref("toolkit.startup.last_success", 1706606926);
user_pref("toolkit.telemetry.cachedClientID", "c814cc00-e9c1-4b39-8d1b-62133f70d847");
user_pref("toolkit.telemetry.previousBuildID", "20231215200246");
